# Generated by Django 5.0.6 on 2025-11-08 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_type', models.CharField(choices=[('weekly', 'Еженедельно'), ('biweekly', 'Раз в N недель'), ('interval', 'Раз в X дней'), ('custom', 'Пользовательские правила')], max_length=20)),
                ('schedule_config', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='programs.programfolder')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('folder', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('weight_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rep_override', models.PositiveIntegerField(blank=True, null=True)),
                ('set_override', models.PositiveIntegerField(blank=True, null=True)),
                ('time_override', models.PositiveIntegerField(blank=True, help_text='Секунды', null=True)),
                ('rest_override', models.PositiveIntegerField(blank=True, help_text='Секунды', null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('custom_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercises.customexercise')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercises.exercise')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_exercises', to='programs.daytemplate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='templateexercise',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('custom_exercise__isnull', True), ('exercise__isnull', False)), models.Q(('custom_exercise__isnull', False), ('exercise__isnull', True)), _connector='OR'), name='templateexercise_exactly_one_source'),
        ),
    ]
