# Generated by Django 5.0.6 on 2025-11-08 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('completed', 'Завершено')], default='pending', max_length=20)),
                ('source_folder_ids', models.JSONField(blank=True, default=list)),
                ('source_template_ids', models.JSONField(blank=True, default=list)),
                ('plan_snapshot', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutSetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_index', models.PositiveIntegerField()),
                ('actual_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('actual_time', models.PositiveIntegerField(blank=True, null=True)),
                ('template_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.templateexercise')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='workouts.workoutday')),
            ],
            options={
                'ordering': ['workout_day', 'template_exercise_id', 'set_index'],
                'unique_together': {('workout_day', 'template_exercise', 'set_index')},
            },
        ),
    ]
