# Generated by Django 5.0.6 on 2025-11-08 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_DB',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('force_en', models.CharField(max_length=64)),
                ('force_ru', models.CharField(max_length=64)),
                ('level_en', models.CharField(max_length=64)),
                ('level_ru', models.CharField(max_length=64)),
                ('mechanic_en', models.CharField(blank=True, max_length=64, null=True)),
                ('mechanic_ru', models.CharField(blank=True, max_length=64, null=True)),
                ('equipment_en', models.CharField(max_length=64)),
                ('equipment_ru', models.CharField(max_length=64)),
                ('category_en', models.CharField(max_length=64)),
                ('category_ru', models.CharField(max_length=64)),
                ('has_weight', models.BooleanField(default=True)),
                ('has_time', models.BooleanField(default=False)),
                ('default_sets', models.PositiveIntegerField(default=3)),
                ('default_reps', models.PositiveIntegerField(default=10)),
                ('default_rest', models.PositiveIntegerField(default=60)),
                ('default_time', models.PositiveIntegerField(blank=True, null=True)),
                ('default_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'ordering': ['name_ru', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=128)),
                ('name_ru', models.CharField(max_length=128)),
                ('is_primary', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscles', to='workouts.exercise_db')),
            ],
            options={
                'verbose_name': 'Мышца упражнения',
                'verbose_name_plural': 'Мышцы упражнений',
                'ordering': ['exercise_id', '-is_primary', 'name_en'],
                'unique_together': {('exercise', 'name_en', 'is_primary')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('text_en', models.TextField()),
                ('text_ru', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='workouts.exercise_db')),
            ],
            options={
                'verbose_name': 'Инструкция упражнения',
                'verbose_name_plural': 'Инструкции упражнений',
                'ordering': ['exercise_id', 'order'],
                'unique_together': {('exercise', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('path', models.CharField(max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workouts.exercise_db')),
            ],
            options={
                'verbose_name': 'Изображение упражнения',
                'verbose_name_plural': 'Изображения упражнений',
                'ordering': ['exercise_id', 'order'],
                'unique_together': {('exercise', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='exercisemuscle',
            index=models.Index(fields=['is_primary', 'name_en'], name='workouts_ex_is_pri_743b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisemuscle',
            index=models.Index(fields=['is_primary', 'name_ru'], name='workouts_ex_is_pri_cdde31_idx'),
        ),
    ]
