# Generated by Django 5.0.6 on 2026-03-03 18:00

import django.core.validators
import workouts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_workoutweighin'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutMusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(storage=workouts.models.MusicStorage(), unique=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a', 'aac', 'webm'])])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Музыкальный трек',
                'verbose_name_plural': 'Музыкальные треки',
                'ordering': ['title', 'file', '-created_at'],
            },
        ),
    ]
