# Generated by Django 5.0.6 on 2026-03-03 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_workoutmusictrack_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutmusictrack',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Пусто = системный трек для всех пользователей', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
