# Generated by Django 5.0.6 on 2026-03-03 21:25

import django.core.validators
import workouts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0014_workoutmusictrack_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutmusictrack",
            name="file",
            field=models.FileField(
                storage=workouts.models.MusicStorage(),
                upload_to=workouts.models.music_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3", "wav", "ogg", "m4a", "aac", "webm"]
                    )
                ],
            ),
        ),
    ]
