# Generated by Django 5.0.6 on 2026-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0015_alter_workoutmusictrack_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutmusictrack",
            name="artist",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
