# Generated by Django 5.0.6 on 2026-03-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_workoutmusictrack_artist'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exercisemuscle',
            new_name='workouts_ex_is_prim_8945b9_idx',
            old_name='workouts_ex_is_pri_743b6a_idx',
        ),
        migrations.RenameIndex(
            model_name='exercisemuscle',
            new_name='workouts_ex_is_prim_44ea03_idx',
            old_name='workouts_ex_is_pri_cdde31_idx',
        ),
        migrations.AlterField(
            model_name='exercise_db',
            name='default_rest',
            field=models.PositiveIntegerField(default=60, help_text='Отдых в секундах'),
        ),
        migrations.AlterField(
            model_name='exercise_db',
            name='default_time',
            field=models.PositiveIntegerField(blank=True, help_text='Время в секундах', null=True),
        ),
    ]
