# Generated by Django 5.2.16 on 2026-09-12 16:28

import django.core.validators
import workouts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0019_techniquereview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutmusictrack",
            name="stream_category",
            field=models.CharField(
                blank=True,
                choices=[("workout", "Тренировка"), ("relax", "Релакс")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workoutmusictrack",
            name="stream_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=500,
                validators=[django.core.validators.URLValidator(schemes=["https"])],
            ),
        ),
        migrations.AlterField(
            model_name="workoutmusictrack",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=workouts.models.MusicStorage(),
                upload_to=workouts.models.music_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3", "wav", "ogg", "m4a", "aac", "webm"]
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="workoutmusictrack",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("file__isnull", False),
                        ("stream_url", ""),
                        ~models.Q(("file", "")),
                    ),
                    models.Q(
                        models.Q(("file__isnull", True), ("file", ""), _connector="OR"),
                        ~models.Q(("stream_url", "")),
                    ),
                    _connector="OR",
                ),
                name="workout_music_exactly_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="workoutmusictrack",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("stream_category", ""), ("stream_url", "")),
                    models.Q(
                        ~models.Q(("stream_url", "")),
                        ~models.Q(("stream_category", "")),
                    ),
                    _connector="OR",
                ),
                name="workout_music_stream_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="workoutmusictrack",
            constraint=models.UniqueConstraint(
                condition=~models.Q(("stream_url", "")),
                fields=("stream_url",),
                name="workout_music_unique_stream_url",
            ),
        ),
    ]
