# Generated by Django 5.0.6 on 2025-11-08 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('target_muscles', models.CharField(help_text='Например: грудь/трицепс', max_length=120)),
                ('has_weight', models.BooleanField(default=True)),
                ('has_time', models.BooleanField(default=False)),
                ('default_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('default_time', models.PositiveIntegerField(blank=True, help_text='Время в секундах', null=True)),
                ('default_reps', models.PositiveIntegerField(default=10)),
                ('default_sets', models.PositiveIntegerField(default=3)),
                ('default_rest', models.PositiveIntegerField(default=60, help_text='Отдых в секундах')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('target_muscles', models.CharField(max_length=120)),
                ('has_weight', models.BooleanField(default=True)),
                ('has_time', models.BooleanField(default=False)),
                ('default_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('default_time', models.PositiveIntegerField(blank=True, help_text='Время в секундах', null=True)),
                ('default_reps', models.PositiveIntegerField(default=10)),
                ('default_sets', models.PositiveIntegerField(default=3)),
                ('default_rest', models.PositiveIntegerField(default=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
                ('base_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_clones', to='exercises.exercise')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
